# Generated by Django 5.1.4 on 2025-01-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contapagar_contareceber_delete_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contareceber',
            name='recebido',
        ),
        migrations.AddField(
            model_name='contareceber',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago')], default='Pendente', max_length=20),
        ),
    ]
