# Generated by Django 5.1.4 on 2025-01-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_contareceber_recebido_contareceber_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contareceber',
            name='status',
        ),
        migrations.AddField(
            model_name='contareceber',
            name='recebido',
            field=models.BooleanField(default=False),
        ),
    ]
