# Generated by Django 5.1.4 on 2025-01-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_contareceber_status_contareceber_recebido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaAReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('pago', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ContaReceber',
        ),
    ]
